### PR TITLE
Create CupertinoIcons diagram

### PR DESCRIPTION
**Pull request by jmagman**
Create a diagram to show `CupertinoIcons`, modeled on the existing [IconDiagram](https://github.com/flutter/assets-for-api-docs/blob/master/packages/diagrams/lib/src/icon.dart).  Use a bell instead of the musical note, which is kind of thin-looking in Cupertino.

Generated icon is:

cupertino_icon

similar to the existing widgets icon asset:
icon

Will be used in a sample in [CupertinoIcons docs](https://api.flutter.dev/flutter/cupertino/CupertinoIcons-class.html) instead of the currently broken `icon gallery preview` (see https://github.com/flutter/flutter/issues/88754 for details on why that's broken): 
Screen Shot 2021-11-04 at 5 17 58 PM

Will be used similarly to the current [`Icons` docs](https://api.flutter.dev/flutter/material/Icons-class.html):
Screen Shot 2021-11-04 at 5 16 32 PM

Adoption in https://github.com/flutter/flutter/pull/93087.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by jmagman** [comment]
>  I added new tests to check the change I am making, or this PR is [test-exempt].

@gspencergoog Is there some way to explicitly test this?  I couldn't find anything for `IconDiagram`.  Or is the generated image good enough to prove it works?

**Comment by gspencergoog** [comment]
> Is there some way to explicitly test this? I couldn't find anything for IconDiagram. Or is the generated image good enough to prove it works?

This repo doesn't really have the test coverage it should have. Ideally, we'd have golden tests for all of the diagrams.

**Comment by gspencergoog** [comment]
There aren't tests for the diagrams, which isn't to say that there *shouldn't* be, but we should probably set up a more comprehensive test infrastructure if we do that.  The CI doesn't even build the diagrams right now, for instance.

**Comment by jmagman** [comment]
> There aren't tests for the diagrams, which isn't to say that there _shouldn't_ be, but we should probably set up a more comprehensive test infrastructure if we do that. The CI doesn't even build the diagrams right now, for instance.

Understood.

**Comment by jmagman** [comment]
@gspencergoog did you have any requested changes for this PR?

**Comment by gspencergoog** [comment]
Sorry, should have been clear about that. No, no requested changes.

**Review by christopherfujino — APPROVED** [review]
LGTM

**Pull request merged**
