### PR TITLE
Supporting assets for TileMode documentation

### PR DESCRIPTION
**Pull request by Hixie**

### CODE REVIEW

**Comment by Hixie** [comment]
cc @abarth

**Comment by abarth** [comment]
Maybe put the dart file in a `lib` directory and add a license block to the top?

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
I've made a number of changes.

Do not land without an engine roll that fixes the engine docs.

**Comment by abarth** [comment]
LGTM

**Comment by Hixie** [comment]
This should be landed with an engine roll that includes https://github.com/flutter/engine/pull/3668 and must land at the same time as https://github.com/flutter/flutter/pull/9936.

**Pull request merged**
