### PR TITLE
Curve generates wrong name

### PR DESCRIPTION
**Pull request by JosepBove**
This change is related with the issue at https://github.com/flutter/flutter/issues/52316.

Currently you are generating an animation named "curve_fact_linear_to_slow_out" and it should be "curve_fact_linear_to_slow_in".

### CODE REVIEW

**Comment by goderbauer** [comment]
You will also have to re-generate the video file by following the steps in the readme: https://github.com/flutter/assets-for-api-docs#generation

**Comment by JosepBove** [comment]
I am on it right now

**Comment by JosepBove** [comment]
I can't do the generation because right now I don't have access to a macOS-linux machine

**Comment by goderbauer** [comment]
FYI: I am fixing the problems reported by the analyzer in https://github.com/flutter/assets-for-api-docs/pull/112.

**Comment by JosepBove** [comment]
Perfect, It would be nice if someone merges this and then generates the video file

**Comment by JosepBove** [comment]
Everything should be ready to merge now

**Comment by goderbauer** [comment]
We can merge as soon as all checks are green.

**Pull request merged**
