### PR TITLE
add focal pointed radial examples

### PR DESCRIPTION
**Pull request by dnfield**
Not 100% sure which folder the PNGs are supposed to go in (tool was putting them in /dart-ui, but looks like they're wanted in /assets/dart-ui so I manually copied them there too).

### CODE REVIEW

**Comment by dnfield** [comment]
This build will fail until flutter/flutter#17826 lands - I think that one is ready to go, but want to be sure I'm correct on the merge order here.

**Comment by gspencergoog** [comment]
This looks pretty good, except that all the assets should be under `assets/dart-ui`, instead of just `dart-ui`.

**Comment by dnfield** [comment]
Removed the ones in `dart-ui`

**Comment by gspencergoog** [comment]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

I'll land this after flutter/flutter#17826 lands.

**Comment by gspencergoog** [comment]
Looks like there's still a build error:
`error • The named parameter 'focal' isn't defined • lib/tile_mode.dart:64:11`

**Comment by dnfield** [comment]
It's because the flutter PR hasn't landed yet.

That one needs some merge conflicts resolved.  I'll look at it this evening.

**Comment by dnfield** [comment]
Should be good now.

**Pull request merged**
