### PR TITLE
Add HLS m3u8 test streaming video file

### PR DESCRIPTION
**Pull request by jmagman**
Add a HTTP Live Streaming (HLS) `.m3u8` file to test in the video_player plugin https://github.com/flutter/flutter/issues/97206

Created from the existing `bee.mp4` video:
```
$ ffmpeg -i bee.mp4 -g 60 -hls_time 2 -hls_list_size 0 -hls_segment_size 500000 bee.m3u8
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by IlyaMax** [comment]
It would be useful to add longer video to example to test issues with video_player in bad internet condition. At least 2 minutes if it possible so buffer couldn't fill up. I'm going to contribute with this in https://github.com/flutter/plugins/pull/4693

**Comment by jmagman** [comment]
> It would be useful to add longer video to example to test issues with video_player in bad internet condition. At least 2 minutes if it possible so buffer couldn't fill up. I'm going to contribute with this in [flutter/plugins#4693](https://github.com/flutter/plugins/pull/4693)

Is there some reason that needs to be HLS and not mp4 or other video format?

**Comment by stuartmorgan** [comment]
We recently switched webview_flutter tests from external URLs to an in-test web server. That's the way we should be moving with video_player as well (it just hasn't been done yet) so more complex use cases like really slow loading should be done via a test server rather than adding more complex assets here.

**Review by stuartmorgan — APPROVED** [review]
LGTM

**Pull request merged**
