### PR TITLE
Generate sweep gradient assets

### PR DESCRIPTION
**Pull request by xqwzts**
This PR modifies the tile_mode generator to also generate screenshots for Sweep gradients (ref: https://github.com/flutter/engine/pull/4950).

To keep all the tile_mode screenshot generation in one library, I had to change from the previous script that layed out both linear and radial gradients in the same a row [with three rows in total, one for each tile mode] to one that follows the [blend_mode](https://github.com/flutter/assets-for-api-docs/blob/master/src/dart-ui/blend_mode.dart) generator's pattern of having an individual mode per page.

That change allows for more space [width] for each item, so the new screenshots are double the width of the previous ones [400x200 vs 200x200].

### CODE REVIEW

**Comment by xqwzts** [comment]
Whoops - the generator depends on `SweepGradient` being implemented in flutter - I have a working version that it used locally to generate the screenshots, but I'm not ready to push that just yet.

I suppose it also wouldn't make sense to push until the `gradient.sweep` changes land in the engine and flutter rolls to an engine version that includes them.

I'll make a separate PR that only includes the screenshots, so those can be used in the `gradient.sweep` documentation, and maybe hold off on landing this PR until the other two have landed?

**Comment by Hixie** [comment]
I think I'd prefer if we kept the images square, because otherwise they get really unwieldy when you stack them.

**Comment by xqwzts** [comment]
I've changed them back to squares (just saw how they're displayed in the [docs](https://docs.flutter.io/flutter/dart-ui/Gradient/Gradient.linear.html) - squares make more sense).

**Comment by Hixie** [comment]
@gspencergoog Any chance you could take this PR and apply the necessary changes to make it use your new API?

**Comment by gspencergoog** [comment]
Sure, I'd be happy to do that.  I've already rewritten the tile_mode generator for that anyhow.

**Comment by xqwzts** [comment]
Closing, superseded by #26

**Pull request closed without merging**
