### PR TITLE
Add assets for ProgressIndicator

### PR DESCRIPTION
**Pull request by sidrao2006**
Assets for flutter/flutter#69498

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by TahaTesser** [comment]
Looks like this PR only contains the diagrams without the code? Is that intentional?

CI issue is fixed https://github.com/flutter/assets-for-api-docs/pull/181, please rebase

**Comment by sidrao2006** [comment]
My initial plan was to add these images before merging https://github.com/flutter/flutter/pull/69498 ..but I removed the references to add the assets before submitting new a PR for the docs.

**Comment by sidrao2006** [comment]
I'll get rid of the 'Circular/Linear Progress Indicator with a background' images.. wouldn't make sense to have 2 images with an interactive sample.

**Review by goderbauer — CHANGES_REQUESTED** [review]
Assets added to this directory should be reproducible (e.g. by running a dart script) to make it easier to update them. See also this note in the readme: https://github.com/flutter/assets-for-api-docs#adding-new-assets

Please also take a look at some of the other assets in this repository and how they are generated to get an idea.

**Comment by Hixie** [comment]
Thanks for your contribution! Since this PR doesn't add the sample code to generate the images, I'm going to close it, as we can't land it as-is. If you're interested in following up please don't hesitate to submit a new PR! I think it's probably also fine just to rely on the dartpad sample code you added since it shows what the progress bars look like too.

**Pull request closed without merging**
