### PR TITLE
add a heroes terminology diagram

### PR DESCRIPTION
**Pull request by xster**
For https://github.com/flutter/flutter/pull/20322

### CODE REVIEW

**Comment by gspencergoog** [comment]
I'd prefer if this were code, but I understand that it's non-trivial to make.  Have you run optpng on the image with the parameters that are in the README.md?

The pubspecs in this repo appear to be out of date. I sent you a PR to review that will fix that so your PR will go green: https://github.com/flutter/assets-for-api-docs/pull/44

**Comment by xster** [comment]
Ya unlike app bars etc, in this case, I unfortunately wouldn't end up using the Hero or anything related to it to create the diagram. The code would just be a WYSIWYM drawer.

**Comment by Hixie** [comment]
This should be code, even if it's just canvas calls or SVG or some such. That way we can easily update it, translate it, etc.

**Comment by Hixie** [comment]
(or, probably most relevant, so that we can eventually make higher-res versions of it easily)

**Comment by xster** [comment]
Ok, I swapped out the image for code. 

Tried looking for a WYSIWYM diagram editor but didn't find any good ones.

**Pull request merged**
