### PR TITLE
Add SweepGradient

### PR DESCRIPTION
**Pull request by gspencergoog**
This adds diagrams for SweepGradient.  This will fail tests until it is actually available in the engine and the framework.

The engine PR is https://github.com/flutter/engine/pull/4950.
The framework PR is  https://github.com/flutter/flutter/pull/17368

### CODE REVIEW

**Comment by gspencergoog** [comment]
@xqwzts, I'll land this once you have both the engine and framework changes committed.

**Comment by Hixie** [comment]
LGTM

**Comment by xqwzts** [comment]
Thanks @gspencergoog I'll be sure to ping a reminder once the framework bits land :)

**Comment by Hixie** [comment]
@xqwzts Where do we stand on the framework side?

**Comment by xqwzts** [comment]
@Hixie Framework PR opened here: https://github.com/flutter/flutter/pull/17368 @gspencergoog was kind enough to review it and I've recently pushed changes addressing his comments.

If you have the time to take a look, could you offer some insight regarding these asserts in the original gradient code: https://github.com/flutter/flutter/pull/17368#discussion_r188694142?

**Pull request merged**
