### PR TITLE
Add butterfly video

### PR DESCRIPTION
**Pull request by mit-mit**
Asset is CC0 Creative Commons, Free for commercial use, No attribution required:
https://pixabay.com/en/videos/flowers-butterfly-nature-garden-5473/

### CODE REVIEW

**Comment by mit-mit** [comment]
Updated assets per feedback. 

These are also Creative Commons, Free for commercial use, No attribution required:
https://pixabay.com/en/videos/butterfly-flower-insect-nature-209/
https://pixabay.com/en/videos/honey-bee-insect-bee-flower-flying-211/

**Comment by Hixie** [comment]
What are these for?

**Comment by mit-mit** [comment]
For https://github.com/flutter/flutter/pull/13195

Is this not the right place for that?

**Comment by Hixie** [comment]
For Gallery assets you want the Gallery assets repo. This is the API docs repo.

**Comment by Hixie** [comment]
(Also, we should make sure to include attribution and licensing information for all assets even if we don't have to, because otherwise when we audit our assets we'll not know what license they are under and we'll remove them.)

**Comment by sethladd** [comment]
Should we delete this branch?

And we have a separate repo for Gallery assets, as @Hixie mentions. To find instructions, check go/flutter-team and/or ping me for instructions :)

**Comment by mit-mit** [comment]
We need to revert first: https://github.com/flutter/assets-for-api-docs/pull/14

**Pull request merged**
