### PR TITLE
Add mp3 test audio file

### PR DESCRIPTION
**Pull request by jmagman**
https://github.com/flutter/plugins/pull/4639 added support for the `video_player` plugin to play mp3s.  Add an mp3 test file to be used by the plugin tests, similar to the existing mp4 test files like [bee.mp4](https://github.com/flutter/assets-for-api-docs/blob/master/assets/videos/bee.mp4)

mp3 is of a rooster: https://pixabay.com/sound-effects/rooster-crowing-7027/

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

### CODE REVIEW

**Comment by jmagman** [comment]
Context: want to test fix for regression at https://github.com/flutter/flutter/issues/97356

**Review by Hixie — APPROVED** [review]
LGTM

**Comment by jmagman** [comment]
I can also choose something less startling, if we're worried about heart attacks during future integration tests.
https://pixabay.com/sound-effects/search/theme/nature/

https://pixabay.com/sound-effects/short-pigeon-wing-flap-14625/
https://pixabay.com/sound-effects/underwater-6236/
https://pixabay.com/sound-effects/birds-taking-off-fly-6277/

**Comment by jmagman** [comment]
I can change it later if the rooster is too much.  🐓

**Pull request merged**
