### PR TITLE
Revert "Add butterfly video"

### PR DESCRIPTION
**Pull request by mit-mit**
Reverts flutter/assets-for-api-docs#13 -- the assets need to be placed elsewhere

### CODE REVIEW

**Comment by Hixie** [comment]
LGTM

**Comment by mit-mit** [comment]
Closing, still need these files

**Comment by sigurdm** [comment]
We still need a README with license info?

**Comment by mit-mit** [comment]
@sigurdm yes, we should, see https://github.com/flutter/assets-for-api-docs/pull/15

**Pull request closed without merging**
