### PR TITLE
Add diagram of `Curves.fastEaseInToSlowEaseOut`

### PR DESCRIPTION
**Pull request by ivirtex**
This PR adds diagram of `Curves.fastEaseInToSlowEaseOut` as part of https://github.com/flutter/flutter/pull/122275

https://user-images.githubusercontent.com/57679865/226763570-1f1e21b7-f615-4827-be31-67831156c15e.mp4

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by ivirtex** [comment]
@MitchellGoodwin, I think this can be merged now, since changes just landed on stable.

**Comment by MitchellGoodwin** [comment]
> @MitchellGoodwin, I think this can be merged now, since changes just landed on stable.

Yes, I'm not sure if the checks pick it up right away, but it should be good to go. Can you rebase to restart the tests?

**Comment by ivirtex** [comment]
I think they fail because Flutter 3.10 uses Dart 3 which doesn't allow unsound null safety and some of the codebase here is written without null safety - thus preventing tests from using latest stable?
Though, I am not sure if that's the case.

**Comment by ivirtex** [comment]
Ok, I think I found the issue, .cirrus.yml specifies to use `dev` Flutter channel for CI, which has been retired.
I changed it to `master`, but this caused a whole chain of problems:
1. `flutter format` has been deprecated and insists on using `dart format`, this requires bumping `flutter_plugin_tools` version to at least 0.13.2+1.
2. The new version of `flutter_plugin_tools` complains about formatting in several files, missing license and incorrect pubspec.yaml in one of the packages.
3. On Flutter 3.10 `ui.window` is deprecated, so ~40 lines of code need to be migrated to the new API.
4. Several constructors are missing `const` keyword, but that's an easy fix with `dart fix`.
5. Several lines must be modified to enable full sound null safety.

I created a draft PR addressing most of these issues: https://github.com/flutter/assets-for-api-docs/pull/215

**Comment by ivirtex** [comment]
Ok, I think I found the issue, .cirrus.yml specifies to use `dev` Flutter channel for CI, which has been retired.
I changed it to `master`, but this caused a whole chain of problems:
1. `flutter format` has been deprecated and insists on using `dart format`, this requires bumping `flutter_plugin_tools` version to at least 0.13.2+1.
2. The new version of `flutter_plugin_tools` complains about formatting in several files, missing license and incorrect pubspec.yaml in one of the packages.
3. On Flutter 3.10 `ui.window` is deprecated, so ~40 lines of code need to be migrated to the new API.
4. Several constructors are missing `const` keyword, but that's an easy fix with `dart fix`.
5. Several lines must be modified to enable full sound null safety.

I created a draft PR addressing most of these issues: https://github.com/flutter/assets-for-api-docs/pull/215

**Comment by MitchellGoodwin** [comment]
@ivirtex can you rebase to see if the update to 3.0 fixes the tests?

**Comment by MitchellGoodwin** [comment]
Looks like it passes the tests, but also it needs to have it's head changed to 'main' instead of 'master_archived'

**Comment by ivirtex** [comment]
@MitchellGoodwin Thanks for reviewing. I can't merge by myself, so I think you, or someone else, must merge this PR manually.

**Pull request merged**
