### PR TITLE
Add HLS (.m3u8) audio-only streaming file

### PR DESCRIPTION
**Pull request by napoleon-na**
Add an audio-only HTTP Live Streaming (HLS) .m3u8 file to test in the video_player_avfoundation plugin https://github.com/flutter/packages/pull/7890

Created from the existing bee.mp4 video:

```
ffmpeg -i bee.mp4 -vn -c:a aac -b:a 128k audio_only.aac

ffmpeg -i audio_only.aac -c:a aac -b:a 128k -ar 44100 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls bee_audio_only.m3u8
```

Related issues: [flutter/flutter#156589](https://github.com/flutter/flutter/issues/156589)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/master/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/master/docs/contributing/Chat.md

### CODE REVIEW

**Comment by stuartmorgan** [comment]
Before this lands, https://github.com/flutter/flutter/issues/156589 needs buy-in from the team that expanding the scope of `video_player_avfoundation` to include audio-only playback as a tested, supported configuration.

**Review by hellohuanlin — APPROVED** [review]
As discussed in the team, we are going to accept the bugfix.

**Comment by napoleon-na** [comment]
@hellohuanlin 
As per the project's guidelines, I've rebased my branch to the latest main branch. Could you approve the workflow again to allow the CI to run? Let me know if there’s anything else I need to address. Thank you!

**Comment by hellohuanlin** [comment]
Done!

**Comment by napoleon-na** [comment]
@hellohuanlin @Piinks 
I believe the issue mentioned in https://github.com/flutter/assets-for-api-docs/pull/253#issuecomment-2477602313 is related to the workflow failure so that I will wait for its resolution.

**Comment by Piinks** [comment]
Rebasing now that the blocking issue has been resolved

**Comment by Piinks** [comment]
Oh actually, permissions for maintainers to make edits is turned off on this PR. 😅 
Rebasing this will resolve it, sorry I cannot trigger that!

**Comment by napoleon-na** [comment]
Could you please approve the workflow again to allow the CI to run?

**Review by Piinks — APPROVED** [review]
LGTM

**Pull request merged**
