### PR TITLE
Add the cupertino system colors mint, cyan, and brown

### PR DESCRIPTION
**Pull request by paldepind**
This PR updates the Cupertino system colors figure with the missing colors mint, cyan and brown as mentioned in https://github.com/flutter/flutter/issues/118970 and as added in the PR https://github.com/flutter/flutter/pull/118971.

I also changed the ordering of the colors to match the order they have in the [Apple HIG](https://developer.apple.com/design/human-interface-guidelines/foundations/color#specifications). This order sorts the colors based on their position in the color wheel (I think) and is much more visually pleasing.

With the three extra colors, the figure did not fit in the viewport available for the diagrams. I henced increased its size a bit in order to fit the figure.

Note the that this PR depends on https://github.com/flutter/flutter/pull/118971 as it uses the new colors added there. Hence it should only be merged after that.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

### CODE REVIEW

**Comment by paldepind** [comment]
The CI failing is expected as the PR only compiles with the  changes from https://github.com/flutter/flutter/pull/118971.

**Comment by MitchellGoodwin** [comment]
This PR is going to need to wait until the updated colors are in stable before it's merged.

**Comment by Hixie** [comment]
It's been about three months since our last stable so the next stable should be soon!

**Comment by MitchellGoodwin** [comment]
@paldepind Hello 👋. The updated colors are in stable now, so would you mind rebasing to restart the tests?

**Comment by MitchellGoodwin** [comment]
@paldepind the base branch was changed from `master_archived` to `main`. Would you be able to rebase on top of main?

**Comment by domesticmouse** [comment]
I've updated the target branch and brought the PR up to date. Going off the previous CI results the code may still require formatting.

**Review by MitchellGoodwin — APPROVED** [review]
LGTM. Thank you for putting this together.

**Pull request merged**
