### PR TITLE
Add a diagram for AppBar

### PR DESCRIPTION
**Pull request by Hixie**
cc @abarth

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

**Comment by sethladd** [comment]
@InMatrix is this useful for widget gallery?

**Comment by Hixie** [comment]
Probably not as-is, but if you want me to produce icons for the widget gallery, assign the bug to me and I'll get to it in due course.

**Comment by InMatrix** [comment]
You mean the widget catalog? I think the current illustration of AppBar borrowed from Material Design is sufficient. This diagram provides useful detail and it is more appropriate in the API doc.

**Pull request merged**
