### PR TITLE
Update the diagrams by regenerating them with the current master.

### PR DESCRIPTION
**Pull request by gspencergoog**
I've done a check of these images and videos to make sure they don't look too crazy, but another set of eyes would be good too (probably easiest to clone my branch and check it locally).

I also updated `generate.dart` to do the ffmpeg conversions in parallel (it's about 70 times faster on my machine!).

### CODE REVIEW

**Comment by Piinks** [comment]
It looks like these may have come out wonky:

- material/material_app_theme_data
- widgets/flow_menu
- widgets/stream_builder_error
- widgets/future_builder_error

but as far as I can tell, these assets aren't actually being used anymore. The api docs for these are using dartpad instead. WDYT? Should we jus remove them?

**Comment by gspencergoog** [comment]
Thanks for finding those!

I did a double take on the `_error` ones too, but I think that they are supposed to show the errors they do.

The material_app_theme_data one does seem to be cutting off the "primaryColor" label, and it is being used [here](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme_data.dart#L158) (and in the API docs [currently there](https://master-api.flutter.dev/flutter/material/ThemeData-class.html#material.ThemeData.2), it looks fine, so indeed a regression).

Like you said, though, the others don't appear to be used, so I'm going to just remove them and see if anything breaks.  (I did check the website too, and it doesn't appear to use them either.)

**Comment by gspencergoog** [comment]
After doing some checking around, it looks like the following assets are never used by the Flutter docs (regular or the website):

```
animation/curve_bounce_in_out.png
animation/curve_bounce_in.png
animation/curve_bounce_out.png
animation/curve_decelerate.png
animation/curve_ease_in_out.png
animation/curve_ease_in.png
animation/curve_ease_out.png
animation/curve_ease.png
animation/curve_elastic_in_out.png
animation/curve_elastic_in.png
animation/curve_elastic_out.png
animation/curve_fast_out_slow_in.png
animation/curve_flipped_curve.mp4
animation/curve_flipped_curve.png
animation/curve_flipped.png
animation/curve_interval.png
animation/curve_linear.png
animation/curve_sawtooth.png
animation/curve_threshold.png
dart-ui/blend_mode_saturation.png
flutter-test/goldens/grid_isolatedDiff.png
flutter-test/goldens/grid_maskedDiff.png
flutter-test/goldens/grid_masterImage.png
flutter-test/goldens/grid_testImage.png
material/no_thumb.png
material/no_tick_mark.png
material/show_bottom_sheet.mp4
material/show_date_picker.mp4
material/show_modal_bottom_sheet.mp4
readme-assets/android_views_test.png
videos/butterfly.mp4
widgets/align_transition_plain.mp4
widgets/animated_builder.mp4
widgets/animated_container.mp4
widgets/decorated_box_transition_plain.mp4
widgets/fade_transition_plain.mp4
widgets/frame_builder_image.mp4
widgets/future_builder.mp4
widgets/positioned_transition_plain.mp4
widgets/relative_positioned_transition_plain.mp4
widgets/rotation_transition_plain.mp4
widgets/scale_transition_plain.mp4
widgets/single_child_scroll_view_expanded.png
widgets/single_child_scroll_view_fixed.png
widgets/size_transition_plain.mp4
widgets/slide_transition_plain.mp4
widgets/sliver_fill_remaining_defers_to_child.mp4
widgets/sliver_fill_remaining_scrolled_beyond.mp4
widgets/sliver_fill_remaining_sizes_child.mp4
widgets/stream_builder.mp4
```

I'm not going to delete them all here, however, I'll do that in another PR.

**Comment by gspencergoog** [comment]
The app_theme_data one appears to be some kind of rounding error in the `LabelPainterWidget`.  If I move it to > 0.5, it places the label in the right place.

**Pull request merged**
