### PR TITLE
Add diagrams for FloatingActionButtonLocation

### PR DESCRIPTION
**Pull request by RoyARG02**
Adds diagrams for the different predefined values of **FloatingActionButtonLocation**.

## Related issues
https://github.com/flutter/flutter/issues/24732

### CODE REVIEW

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

**Comment by gspencergoog** [comment]
Sorry, could you also sort the dependencies in the `pubspec.yaml` too?  I know your didn't introduce the problem, but it would help the analyzer test pass.

**Comment by RoyARG02** [comment]
Hello @gspencergoog the CI is failing on deprecated parameters.

Should I just change the code accordingly? Or do I need to regenerate the assets too?

**Comment by gspencergoog** [comment]
Sorry, I didn't realize this repo was in such a mess.

I fixed all the analyzer problems and updated the diagrams in https://github.com/flutter/assets-for-api-docs/pull/124

Just pull again, resolve any conflicts, and you should be good to go.

**Pull request merged**
