### PR TITLE
Add diagrams for Canvas.drawArc and Path.addArc

### PR DESCRIPTION
**Pull request by PixelToast**
This PR adds diagrams for arcs 😺

canvas_draw_arc:
canvas_draw_arc

path_add_arc.png:
path_add_arc

path_add_arc_ccw.png:
path_add_arc_ccw

### CODE REVIEW

**Comment by gspencergoog** [comment]
Hey, that's a cool diagram!

When I look at [the counter clockwise one](https://github.com/flutter/assets-for-api-docs/pull/197/files#diff-760b0b985254104e1cb33c87230b754428bb1903e5184377470555b78baa03be), it seems like the black dotted line around the outside is escaping the square.

Maybe some transparency and color would help to show the start angle, instead of the dashed lines?

Also, I feel like an arrow on or near the blue line (or even both the start angle and arc lines) might not be a bad idea to show which direction is "positive" on the arc.

**Comment by PixelToast** [comment]
New version with arrows and fixed text alignment:

canvas_draw_arc

path_add_arc

path_add_arc_ccw

**Comment by gspencergoog** [comment]
Oh, that's much nicer!  Could you just do one more small thing: just shrink the overall size of the arcs so that they all (including the black one) fit inside of the grey box with just a little padding? The black dotted arc in the CCW one still looks like it's outside the box.

**Review by gspencergoog — APPROVED** [review]
32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d

OK, the diagrams look great now.
Thanks for adding these!

**Comment by Hixie** [comment]
This is fantastic.

**Pull request merged**
